name: Check GitHub Secrets

on:
  workflow_dispatch:

jobs:
  check-secrets:
    name: Verify Secrets Configuration
    runs-on: ubuntu-latest
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      
    - name: 🔍 Check if secrets are configured
      run: |
        echo "🔍 Checking GitHub Secrets configuration..."
        echo ""
        
        # Check AWS_ACCESS_KEY_ID
        if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
          echo "❌ AWS_ACCESS_KEY_ID: NOT CONFIGURED"
          MISSING_SECRETS=true
        else
          echo "✅ AWS_ACCESS_KEY_ID: Configured"
        fi
        
        # Check AWS_SECRET_ACCESS_KEY
        if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
          echo "❌ AWS_SECRET_ACCESS_KEY: NOT CONFIGURED"
          MISSING_SECRETS=true
        else
          echo "✅ AWS_SECRET_ACCESS_KEY: Configured"
        fi
        
        echo ""
        
        if [ "$MISSING_SECRETS" = "true" ]; then
          echo "🚨 MISSING SECRETS DETECTED!"
          echo ""
          echo "Please configure the following secrets in GitHub:"
          echo "1. Go to: Settings → Secrets and variables → Actions"
          echo "2. Add: AWS_ACCESS_KEY_ID"
          echo "3. Add: AWS_SECRET_ACCESS_KEY"
          echo ""
          echo "📖 For detailed instructions, see AWS_SETUP_GUIDE.md"
          exit 1
        else
          echo "🎉 All secrets are configured!"
          echo "Ready to test AWS connectivity..."
        fi
        
    - name: 🔧 Test AWS credentials (only if secrets exist)
      if: success()
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        echo "🔧 Testing AWS credentials..."
        
        # Test AWS CLI connectivity
        if aws sts get-caller-identity; then
          echo ""
          echo "✅ SUCCESS: AWS credentials are working!"
          echo ""
          echo "📋 Account details:"
          aws sts get-caller-identity --output table
          
        else
          echo ""
          echo "❌ FAILED: AWS credentials are invalid!"
          echo ""
          echo "🔧 Troubleshooting steps:"
          echo "1. Verify AWS_ACCESS_KEY_ID is correct"
          echo "2. Verify AWS_SECRET_ACCESS_KEY is correct"
          echo "3. Check if IAM user has necessary permissions"
          echo "4. Ensure the access keys are active (not deleted)"
          echo ""
          echo "📖 See AWS_SETUP_GUIDE.md for detailed setup instructions"
          exit 1
        fi
        
    - name: 🪣 Quick S3 test (only if AWS works)
      if: success()
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-1
      run: |
        echo "🪣 Testing S3 access..."
        
        # List buckets to test S3 permissions
        if aws s3 ls; then
          echo "✅ S3 access is working!"
          echo ""
          echo "📋 Available buckets:"
          aws s3 ls
        else
          echo "❌ S3 access failed!"
          echo "Please check IAM permissions for S3"
        fi